### ISSUE TITLE
Decide whether a Thread requires a root

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#248]
Should cob::Thread require a root?

It allows creating Thread's without a root, yet appears to require it via it's Threat::new().  Conceptually a Thread can be commented on concurrently, meaning it could have multiple first comments (roots?).

A Thread has a maximum of one root:
```
pub fn root(&self) -> Option<(&CommentId, &Comment)>
```

New Thread's require one comment:
```
pub fn new(id: CommentId, comment: Comment)
```

Thread's default return an empty Thread:
```
let t = Thread::default()
assert_eq!(None, t.root());
```

**Comment by cloudhead** [comment]
To preserve the `Semilattice` properties, `Thread` must work without a root. This is why `root()` returns `Option`. I'd like to keep this property of threads because it's useful. Now there's the question of whether a Thread should allow more than one root.. I think when a thread is created without a root, then it may end up with multiple roots.. But this means we can't get the author/timestamp from the root in that case. This is probably fine though, if we get those from the parent object (issue, or revision).

**Comment by slack-coder** [comment]
I recommend instead making Threads stricter and expect one or more comments.  Without any comments a thread is conceptually non-existent, and could be expressed as an Option<Thread>.

Thread's with multiple roots will never overlap, because they can reply to at most one comment.  Therefore a Thread with one or more roots is best expressed as a [Thread].

This way `Thread`s will be simpler, and these exceptions will be expressed in the context they exist in.  For example, Issue{ Thread } whereas Patch::Revision{ [Thread] }.  Though in the case of revisions, we could keep the root comment empty or give some information even if its only slightly helpful.

**Comment by cloudhead** [comment]
The above would make sense normally, but none of this plays nicely when working with CRDTs. We need objects that have a valid "empty" value, when dealing with containers, which `Thread` is.. Nothing's stopping you from enforcing rules on the application layer though.

**Comment by slack-coder** [comment]
What part of CRDT's prevent a `Thread` with a single root comment being considered empty?

**Comment by slack-coder** [comment]
After discussion, there was a misconception.  Thread's have multiple roots as it is made to have many comments with 'reply to' set to None.
