### ISSUE TITLE
Remove documentation test `git remote` dependency

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/heartwood#484]
The documentation tests in radicle-cli have an external dependence on 'radicle-remote-helper'.  A compatible version of the helper must be installed on the system running the tests.

To reduce friction this causes, the documentation tests which rely on the helper are not run during standard operation of `cargo test`.  They are marked 'ignore' and are run explicitly.

From our continuous integration:
```
          # Workaround for client document tests dependent on the remote
          # helper. Tests which rely on these should be marked #[ignore] and
          # whitelisted here.
          #
          # Marking them as 'ignored' will allow local testing to work as
          # expected, yet allow these document tests to be covered during
          # integration testing.
          cargo install --locked --debug --path ./radicle-remote-helper
          cargo test --all --all-features rad_patch -- --ignored
          cargo test --all --all-features rad_workflow -- --ignored
```

Could there be a way to remove the external dependency?

**Comment by cloudhead** [comment]
I don't think so, because we need it for `git push rad` / `rad push`. It's only possible to mock when calling library functions, but here, `git push` will expect it to exist.

Instead, I propose that we install the binary in the tests that need it. This is possible with for eg. https://docs.rs/escargot/latest/escargot/

We'd have to see if it's worth depending on that crate or not, but that's the idea.
